### ISSUE TITLE
StackStorm exchange blocked in India

### ISSUE THREAD

**Issue by AbhyudayaSharma** [StackStorm-Exchange/exchange-incubator#173] opened 2022-01-11 12:19 UTC
Sorry if this is the wrong place to post this issue but StackStorm exchange seems to be blocked in India. The served site even has a valid TLS certificate issued by Cloudflare.

![image](https://user-images.githubusercontent.com/11471599/148941157-5d114d58-5d7a-4ffb-80d1-8d46f37b7880.png)

![image](https://user-images.githubusercontent.com/11471599/148941239-3eca845a-53fc-4d60-95d3-d6db1a07a4a9.png)

**Comment by AbhyudayaSharma** [comment] 2022-01-11 12:26
It looks like [this](https://github.com/captn3m0/hello-cloudflare/blob/main/README.md) is the reason for the block.

**Comment by abhi1693** [comment] 2022-01-11 13:31
@AbhyudayaSharma It's not completely blocked. It works sometimes, check [this](https://github.com/StackStorm-Exchange/index/issues/26). It's an intermittent issue but happens alot.

**Comment by armab** [comment] 2022-01-11 23:15
Thanks for more info and research, https://github.com/captn3m0/hello-cloudflare/blob/main/README.md is really helpful to understand the root cause better.

I'm also going through https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b and https://gist.github.com/zbeekman/ac6eeb41ea7980f410959b13416d74c9 and playing with the GH pages HTTPS settings as there were some issues configuring HTTPS with github pages.

**Comment by armab** [comment] 2022-01-11 23:57
I could set up SSL for GH Pages (exchange.stackstorm.org and index.stackstorm.org), so it should be secure along the entire chain.
Before:
![image](https://user-images.githubusercontent.com/1533818/149038909-ce8cc8fb-af72-49bc-8895-322631e7c0ea.png)
Now:
![image](https://user-images.githubusercontent.com/1533818/149038870-fab61d7f-e507-41ac-a36f-d50ddb8ecea2.png)

However, per https://gist.github.com/zbeekman/ac6eeb41ea7980f410959b13416d74c9, we might have an issue in 1 year when Github tries to renew its certificate and it'll fail because of the CF proxy. 

---

@abhi1693 @AbhyudayaSharma Please check if you still got these issues with the StackStorm Exchange being blocked and report back.

**Comment by AbhyudayaSharma** [comment] 2022-01-12 06:38
@armab Thanks for the fix. It looks to be working now.

> However, per https://gist.github.com/zbeekman/ac6eeb41ea7980f410959b13416d74c9, we might have an issue in 1 year when Github tries to renew its certificate and it'll fail because of the CF proxy. We'll see.

You could remove Cloudflare entirely and serve directly from GitHub pages now that TLS is enabled. If I remember correctly, they use Fastly so there should not be much difference in performance.

**Comment by armab** [comment] 2022-01-12 20:18
We can't remove CloudFlare due to some CF functionality we depend on for Exchange to work properly.

**Comment by armab** [comment] 2022-01-12 20:21
Anyway, sounds like it's fixed now.
Thanks for the report and pointers.

Closing as solved. Please re-open if the issue appears again.

**Closed by armab** 2022-01-12 20:21 UTC
Labels: bug, maintenance
